version: "3.0"

services:

  solr1:
    image: solr:8
    ports:
      - "8983:8983"
    volumes:
      - ./historian/wait-for-it.sh:/usr/bin/wait-for-it.sh
      - ./historian/solr.xml:/opt/solr/server/solr/solr.xml
      - ./historian/solr-metrics-influxdb-1.1.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/solr-influxdb-reporter.jar
      - ./historian/metrics-influxdb-0.9.3.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/metrics-influxdb-0.9.3.jar
      - ./historian/grafana-register.sh:/opt/grafana-register.sh
      - ./historian/solr-dashboard.json:/opt/solr-dashboard.json
    command: /bin/bash -c "/usr/bin/wait-for-it.sh -h zookeeper -p 2181 -t 0 && /usr/bin/wait-for-it.sh -h influxdb -p 8086 -t 0 && /usr/bin/wait-for-it.sh -h grafana -p 3000 -t 0 && cd /opt && /opt/grafana-register.sh; /opt/solr/bin/solr -c -f -z zookeeper:2181 -m 1g"
    links:
      - influxdb
      - grafana
      - zookeeper
    networks:
      - logisland

  solr2:
    image: solr:8
    volumes:
      - ./historian/wait-for-it.sh:/usr/bin/wait-for-it.sh
      - ./historian/solr.xml:/opt/solr/server/solr/solr.xml
      - ./historian/solr-metrics-influxdb-1.1.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/solr-influxdb-reporter.jar
      - ./historian/metrics-influxdb-0.9.3.jar:/opt/solr/server/solr-webapp/webapp/WEB-INF/lib/metrics-influxdb-0.9.3.jar
    command: /bin/bash -c "/usr/bin/wait-for-it.sh -h zookeeper -p 2181 -t 0; /opt/solr/bin/solr -c -f -z zookeeper:2181 -m 1g"
    links:
      - influxdb
      - zookeeper      
    networks:
      - logisland

  influxdb:
    image: influxdb:latest
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
        #env_file:
        #- 'env.influxdb'
    networks:
      - logisland

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
        #env_file:
        #- 'env.grafana'
    links:
      - influxdb
    networks:
      - logisland
