version: '3'
services:

  # ES container
  # make sure to increase vm.max_map_count kernel setting like documented here :
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    environment:
      - ES_JAVA_OPT='-Xms1G -Xmx1G'
      - cluster.name=es-logisland
      - http.host=0.0.0.0
      - transport.host=0.0.0.0
      - xpack.security.enabled=false
      - discovery.type=single-node
    hostname: elasticsearch
    image: 'docker.elastic.co/elasticsearch/elasticsearch:6.6.2'
    ports:
      - '9200:9200'
      - '9300:9300'
    networks:
      - logisland

  # Kibana container
  kibana:
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    image: 'docker.elastic.co/kibana/kibana:6.6.2'
    ports:
      - '5601:5601'
    networks:
      - logisland
